#!/bin/sh
#-
# Copyright (C) 2011, 2012, 2013, 2014 Mikolaj Izdebski
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e
IFS=' ''	''
'

if ! test -r autogen.sh; then
  echo autogen.sh: need to be called from top source directory >&2
  exit 1
fi

# Option -r removes autogenerated files.
if test x"$1" = x-r; then
  rm -Rf autom4te.cache install-sh missing depcomp compile
  rm -f configure aclocal.m4 INSTALL Makefile.in config.h.in
  exit 0
fi

aclocal
autoconf
autoheader
automake --add-missing --copy
