.TH LBZDIFF 1
.SH NAME
lbzcmp, lbzdiff \- compare compressed files
.SH SYNOPSIS
.B lbzcmp
[ cmp_options ] file1
[ file2 ]
.br
.B lbzdiff
[ diff_options ] file1
[ file2 ]
.SH DESCRIPTION
.I  Lbzcmp
and
.I lbzdiff
are used to invoke the
.I cmp
or the
.I diff
program on files compressed via
.IR lbzip2 "."
All options specified are passed directly to
.I cmp
or
.IR diff "."
If only
.I file1
is specified, it is compared to the uncompressed contents of
.IR file1 ".bz2."
If two files are specified, their contents (uncompressed if necessary) are fed to
.I cmp
or
.IR diff "."
The input files are not modified.
The exit status from
.I cmp
or
.I diff
is preserved.
.SH "SEE ALSO"
cmp(1), diff(1), lbzmore(1), lbzgrep(1), lbzforce(1), lbzip2(1), lbzexe(1)
.SH BUGS
Messages from the
.I cmp
or
.I diff
programs may refer to file names such as "\-" instead of to the file
names specified.
